name: Continuous Integration
permissions: read-all

on:
  pull_request:
    branches:
      - main

concurrency:
  # yamllint disable-line rule:line-length
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]
        tox: [36, 37, 38, 39, 310, 311, pep8, black-ci]
        include:
          - python: 3.6
            tox: 36
          - python: 3.7
            tox: 37
          - python: 3.8
            tox: 38
          - python: 3.9
            tox: 39
          - python: 3.10
            tox: 310
          - python: 3.11
            tox: 311
          - python: 3.11
            tox: pep8
          - python: 3.11
            tox: black-ci
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3.3.0

      - name: Setup Python ğŸ”§
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{Â matrix.python }}

      - name: Build ğŸ”§ & Test ğŸ”
        run: |
          pip install tox
          tox -e ${{ matrix.tox }}
