name: Continuous Integration
permissions: read-all

on:
  pull_request:
    branches:
      - main

concurrency:
  # yamllint disable-line rule:line-length
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - python: "3.10"
            task: check
          - python: "3.11"
            task: check
          - python: "3.12"
            task: check
          - python: "3.13"
            task: check
          - python: "3.14"
            task: check
          - python: "3.14"
            task: lint
          - python: "3.14"
            task: mypy
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup uv ğŸ”§
        uses: astral-sh/setup-uv@v5

      - name: Build ğŸ”§ & Test ğŸ”
        run: uv run --python ${{ matrix.python }} poe ${{ matrix.task }}
